language: python
services:
  - postgresql
python:
  - 2.7
install:
  - pip install -r dev-requirements.txt
before_script:
  - psql -c 'create database earthvibration;' -U postgres
  - cp earthvibration/settings_secret.py.example earthvibration/settings_secret.py
  - sed -i -e 's/getpass\.getuser()/\"postgres\"/g' earthvibration/settings_secret.py
  - python manage.py migrate --noinput
script:
  - python manage.py test
